### ISSUE TITLE
International logo

### ISSUE THREAD

**Issue by cadars** [WICG/webmonetization#172]
Currently the logo uses the dollar sign: while it's well understood and appreciated as a symbol of money in most(?) countries, it also specifically means dollars or pesos, and is generally US-centric.

The generic currency symbol (¤) isn't well known, so what would be a better option? The cent (¢) comes to mind, but it's not universal either.

**Comment by marcoscaceres** [comment]
Agree... we should probably engage some designers to come up with a unique currency symbol or logo - Keeping in mind that WM is not a currency, it's a way of leveraging a network to enable (micro/streaming)payments.  

For inspiration:
https://coinmarketcap.com/all/views/all/

**Comment by uchibeke** [comment]
Adding an update from the Web Monetization Workshop, where we discussed:

### Logo and Brand
- Recognizable
- Icon vs Logo

### Call to Action for Web Monetization
- The need for a CTA for Web Monetization instead of CTA for individual providers
- Potentially creating a Working group, Web Monetization branding working group/task force with [Erica](https://community.webmonetization.org/ericahargreave) spearheading this


We went further to discuss _Word_ to describe what the user has that allows them access to the Web Monetized content. We considered: 
- "WebMo enabled"
- "a WebMo subscription"
- "a Web Multipass"
- " a WebMo wallet"
- Web wallet?
... (similar to, if you see an RSS logo, the question is 'do you have an RSS reader?')

Douglas Kimani used the analogy of wifi, an icon, and how to socialize it.

**Comment by networkimprov** [comment]
Also consider that WM could compensate members of a site, not just its owners. So branding & slogans could encompass both receiving & making payments.

More terms ideas:
- a Web Bank
- a WebCard
- WebCredit
- WebDebit

FWIW, "WebMo" sounds more like a company than an Internet standard to my ear.

**Comment by huijing** [comment]
The logo is now updated.
