### ISSUE TITLE
Maximum number of connections?

### ISSUE THREAD

**Issue by pp-koch** [WICG/webmonetization#243]
Since implementations can decide on the maximum number of monetization connections per document, what number is the extension going to support?

**Comment by marcoscaceres** [comment]
I imagine that will changes quite dramatically over time... it might not be good to make any assumptions as the connection limit is shared across the entire browser... but the recommendation is to limit the number as much as possible because `<reasons>` (i.e., consumes resources of device, could waste battery, won't get you any more money, etc.).

**Comment by pp-koch** [comment]
I just wanted to include the current number of connections of the current extension as an example. But naming these reasons is a good idea.

**Comment by marcoscaceres** [comment]
@sublimator 👆… any idea? 

If you do list the limit, make sure it’s super clear that it can change.

**Comment by sublimator** [comment]
For better or worse, we never put any limit on it :)

**Comment by marcoscaceres** [comment]
That’s great to hear actually.

**Comment by marcoscaceres** [comment]
Closing as answered.
