### ISSUE TITLE
Refactor the "Exclusive Content Generator" to use link instead of meta tags

### ISSUE THREAD

**Issue by AlexLakatos** [WICG/webmonetization#318]
Currently, https://webmonetization.org/exclusive-content helps you generate an html snippet and a script to manage showing exclusive content on a page for web monetized visitors.

We should update the page & generator functionality to conform with the new Web Monetization spec, that uses link tags instead of meta tags. https://webmonetization-preview.netlify.app/specification.html

We should also remove the use of the receipt verifier, see #317.

Note: link tags are supported throughout the document, not just in the head. 

We might also need to update the CloudFlare service worker associated with the page; some of the logic resides there: https://github.com/WICG/webmonetization/tree/main/workers/exclusive-content

**Comment by melissahenderson** [comment]
I've removed the hidden content from the docs and saved them locally. This task still needs to be completed if we want to offer the generator.

**Comment by melissahenderson** [comment]
Related: #337

**Comment by melissahenderson** [comment]
Based on conversations during the Web Monetization work week, I've decided to close this and the related issue. 

- This functionality has been completely hidden from the docs since at least June 2023.
- The script is obsolete due to updates to the WM spec and needs to be reworked.
- The functionality has logic residing in a CloudFlare service worker that we must maintain.

If we feel that an exclusive content generator would still be beneficial, I'd prefer for its creation to be handled by a member of the WM community and added to our list of libraries.
